"""Local dev server for the Cross-Channel Marketing Performance Dashboard.
Run: python3 app.py  →  open http://localhost:5000

This is for local exploration only — the published artifact is the static
snapshot generated by generate_static_site.py (see README).
"""

import json
import os

from dotenv import load_dotenv
from flask import Flask
from markupsafe import Markup

from pipeline import build_dashboard
from templates import DASHBOARD_TEMPLATE, make_environment

load_dotenv()

app = Flask(__name__)
_env = make_environment()
_dashboard = None  # built once, lazily, on first request


@app.route("/")
def index():
    global _dashboard
    if _dashboard is None:
        _dashboard = build_dashboard()
    tmpl = _env.from_string(DASHBOARD_TEMPLATE)
    return tmpl.render(
        live=True,
        summary=_dashboard["summary"],
        channels=_dashboard["channels"],
        insights=_dashboard["insights"],
        charts_json=Markup(json.dumps(_dashboard["charts"])),
    )


@app.route("/api/refresh", methods=["POST"])
def api_refresh():
    global _dashboard
    _dashboard = build_dashboard()
    return {"ok": True}


if __name__ == "__main__":
    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port, debug=True)
